# Generated by Django 6.1 on 2026-08-19 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('sucursales', '0002_crear_sucursal_central'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='sucursales.sucursal'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('sucursal', 'nombre'), name='categoria_unica_por_sucursal'),
        ),
    ]
