# Generated by Django 6.1 on 2026-08-19 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_asignar_categorias_a_sucursal_central'),
        ('sucursales', '0002_crear_sucursal_central'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='productos.categoria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='productos.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='sucursales.sucursal')),
            ],
            options={
                'verbose_name': 'inventario por sucursal',
                'verbose_name_plural': 'inventarios por sucursal',
                'constraints': [models.UniqueConstraint(fields=('producto', 'sucursal'), name='inventario_unico_por_sucursal')],
            },
        ),
    ]
