# Generated by Django 6.1 on 2026-08-19 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_crear_inventario_sucursal_central'),
        ('sucursales', '0002_crear_sucursal_central'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='sucursales.sucursal'),
            preserve_default=False,
        ),
    ]
