# Generated by Django 6.1 on 2026-08-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_categoria_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
